# Generated by Django 5.0.1 on 2024-02-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emplyno', models.IntegerField(primary_key='True', serialize=False)),
                ('emplyname', models.CharField(max_length=20)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
