# Generated by Django 5.0.1 on 2024-02-07 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0002_remove_employee_id_alter_employee_empno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dptno', models.IntegerField(primary_key='True', serialize=False)),
                ('dptname', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='dptno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbapp.department'),
        ),
    ]
