# Generated by Django 5.0.1 on 2024-02-09 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0003_department_employee_dptno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='dptno',
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbapp.department'),
        ),
    ]
