# Generated by Django 5.0.1 on 2024-02-09 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0004_remove_employee_dptno_employee_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
    ]
