# Generated by Django 5.0.1 on 2024-02-21 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0006_employee_department_alter_department_dptno'),
    ]

    operations = [
        migrations.CreateModel(
            name='base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empno', models.IntegerField()),
                ('empname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='base1',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dbapp.base')),
            ],
            bases=('dbapp.base',),
        ),
        migrations.CreateModel(
            name='base2',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dbapp.base')),
                ('salary', models.IntegerField()),
            ],
            bases=('dbapp.base',),
        ),
        migrations.CreateModel(
            name='base3',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dbapp.base')),
                ('address', models.CharField(max_length=100)),
            ],
            bases=('dbapp.base',),
        ),
        migrations.CreateModel(
            name='base4',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dbapp.base')),
                ('region', models.CharField(max_length=50)),
            ],
            bases=('dbapp.base',),
        ),
    ]
