# Generated by Django 5.0.1 on 2024-02-21 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0007_base_base1_base2_base3_base4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='base4',
            name='base_ptr',
        ),
        migrations.RemoveField(
            model_name='base1',
            name='base_ptr',
        ),
        migrations.RemoveField(
            model_name='base3',
            name='base_ptr',
        ),
        migrations.DeleteModel(
            name='base2',
        ),
        migrations.DeleteModel(
            name='base4',
        ),
        migrations.DeleteModel(
            name='base1',
        ),
        migrations.DeleteModel(
            name='base',
        ),
        migrations.DeleteModel(
            name='base3',
        ),
    ]
