# Generated by Django 5.0.1 on 2024-02-21 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0009_base01_base02_base03_base04'),
    ]

    operations = [
        migrations.CreateModel(
            name='base5',
            fields=[
            ],
            options={
                'ordering': ['salary'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dbapp.employee',),
        ),
    ]
