# Generated by Django 5.0.1 on 2024-02-21 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0010_base5'),
    ]

    operations = [
        migrations.DeleteModel(
            name='base01',
        ),
        migrations.DeleteModel(
            name='base02',
        ),
        migrations.DeleteModel(
            name='base03',
        ),
        migrations.DeleteModel(
            name='base04',
        ),
    ]
