# Generated by Django 5.0.1 on 2024-02-21 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0011_delete_base01_delete_base02_delete_base03_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='base5',
        ),
    ]
