# Generated by Django 5.0.1 on 2024-02-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0012_delete_base5'),
    ]

    operations = [
        migrations.CreateModel(
            name='classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
