# Generated by Django 5.0.1 on 2024-02-21 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0015_base01_base02_delete_base1_delete_base2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='base01',
            new_name='phase01',
        ),
        migrations.RenameModel(
            old_name='base02',
            new_name='phase02',
        ),
    ]
