# Generated by Django 5.0.1 on 2024-02-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0017_book1_delete_phase01_delete_phase02'),
    ]

    operations = [
        migrations.CreateModel(
            name='book2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookno', models.IntegerField()),
                ('bookname', models.CharField(max_length=20)),
                ('bookcolour', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
