# Generated by Django 5.0.1 on 2024-02-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0019_employeebooks'),
    ]

    operations = [
        migrations.CreateModel(
            name='cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.IntegerField()),
                ('model', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='drivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licno', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('car', models.ManyToManyField(to='dbapp.cars')),
            ],
        ),
    ]
