# Generated by Django 5.0.1 on 2024-02-26 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0021_employee_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employeeBooks',
        ),
    ]
