# Generated by Django 5.0.1 on 2024-02-26 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0022_delete_employeebooks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='book1',
        ),
        migrations.DeleteModel(
            name='book2',
        ),
    ]
