# Generated by Django 5.0.1 on 2024-02-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0023_delete_book1_delete_book2'),
    ]

    operations = [
        migrations.CreateModel(
            name='book1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookno', models.IntegerField()),
                ('bookname', models.CharField(max_length=20)),
                ('bookauthor', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='book2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookno', models.IntegerField()),
                ('bookname', models.CharField(max_length=20)),
                ('bookcolour', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='employeeBooks',
            fields=[
            ],
            options={
                'ordering': ['salary'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dbapp.employee',),
        ),
    ]
