# Generated by Django 5.0.1 on 2024-02-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0002_remove_user_id_alter_user_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('option1', models.CharField(max_length=50)),
                ('option2', models.CharField(max_length=50)),
                ('option3', models.CharField(max_length=50)),
                ('option4', models.CharField(max_length=50)),
                ('correct_answer', models.CharField(max_length=50)),
            ],
        ),
    ]
